<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Linear-Regression" data-toc-modified-id="Linear-Regression-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Linear Regression</a></span><ul class="toc-item"><li><span><a href="#Concept" data-toc-modified-id="Concept-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Concept</a></span></li><li><span><a href="#Class-Linear" data-toc-modified-id="Class-Linear-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Class Linear</a></span></li><li><span><a href="#Custom-Module" data-toc-modified-id="Custom-Module-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Custom Module</a></span></li></ul></li></ul></div>

# Linear Regression

## Concept

$y = b + wx$

x: predictor (independent) variable

y: target (dependent) variable

b: bias

w: weight

In [2]:
import torch

w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

def forward(x):
    y = w * x + b
    return y

x = torch.tensor([1.0])
yhat = forward(x)

print(yhat)

tensor([1.], grad_fn=<AddBackward0>)


In [3]:
x = torch.tensor([[1.0], [2.0]])
yhat = forward(x)

print(yhat)

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


## Class Linear

To create a linear model, and try to forward input

In [7]:
from torch.nn import Linear

torch.manual_seed(1)

chosen_model = Linear(in_features=1, out_features=1)
print(list(chosen_model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
tensor([-0.4414], grad_fn=<AddBackward0>)


In [ ]:
x = torch.tensor([0.0])
yhat = chosen_model(x)

print(yhat)

In [8]:
x = torch.tensor([[1.0], [2.0]])
yhat = chosen_model(x)

print(yhat)

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)


## Custom Module
To create a custom model by custom module

In [11]:
import torch.nn as nn

class My_Linear_Model(nn.Module):
    def __init__(self, in_size, out_size):
        super(My_Linear_Model, self).__init__()
        self.linear = nn.Linear(in_size, out_size)

    def forward(self, x):
        out = self.linear(x)
        return out
    

In [12]:
chosen_model = My_Linear_Model(1, 1)

chosen_model.state_dict()

OrderedDict([('linear.weight', tensor([[-0.1939]])),
             ('linear.bias', tensor([0.4694]))])

In [17]:
# Change the parameter manually
# Set b = -0.4414
# Set w = 0.5153

chosen_model.state_dict()['linear.weight'].data[0] = torch.tensor([0.5153])
chosen_model.state_dict()['linear.bias'].data[0] = torch.tensor([-0.4414])

print(list(chosen_model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [18]:
x = torch.tensor([[1.0], [2.0]])
yhat = chosen_model(x)

print(yhat)

tensor([[0.0739],
        [0.5892]], grad_fn=<AddmmBackward>)


In [23]:
### model.state_dict()

print("Python Dictionary:\n", chosen_model.state_dict())
print("================================================================")
print("Keys:\n", chosen_model.state_dict().keys())
print("================================================================")
print("Values:\n", chosen_model.state_dict().values)

Python Dictionary:
 OrderedDict([('linear.weight', tensor([[0.5153]])), ('linear.bias', tensor([-0.4414]))])
Keys:
 odict_keys(['linear.weight', 'linear.bias'])
Values:
 <built-in method values of collections.OrderedDict object at 0x000000001DC43CC0>
