<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Basic-Tensor-Operation" data-toc-modified-id="Basic-Tensor-Operation-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Basic Tensor Operation</a></span><ul class="toc-item"><li><span><a href="#1-Dimension-Tensor" data-toc-modified-id="1-Dimension-Tensor-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>1-Dimension Tensor</a></span><ul class="toc-item"><li><span><a href="#Data-Type-and-Tensor-Type" data-toc-modified-id="Data-Type-and-Tensor-Type-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Data Type and Tensor Type</a></span></li></ul></li><li><span><a href="#Conversion-of-Tensors" data-toc-modified-id="Conversion-of-Tensors-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Conversion of Tensors</a></span><ul class="toc-item"><li><span><a href="#Convert-between-tensor-and-numpy-array" data-toc-modified-id="Convert-between-tensor-and-numpy-array-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Convert between tensor and numpy array</a></span></li><li><span><a href="#Convert-between-tensor-and-pandas" data-toc-modified-id="Convert-between-tensor-and-pandas-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Convert between tensor and pandas</a></span></li><li><span><a href="#Convert-between-tensor-and-python-list" data-toc-modified-id="Convert-between-tensor-and-python-list-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Convert between tensor and python list</a></span></li><li><span><a href="#Element-of-tensor" data-toc-modified-id="Element-of-tensor-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>Element of tensor</a></span></li></ul></li></ul></li><li><span><a href="#Index-and-slicing" data-toc-modified-id="Index-and-slicing-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Index and slicing</a></span></li></ul></div>

***

# Basic Tensor Operation

## 1-Dimension Tensor

### Data Type and Tensor Type

![Data type](https://i.imgur.com/RHYCcK2.png)

In [1]:


import torch

a = torch.tensor([1,2,3,4,5])

print(a[0])
print(a.dtype)
print(a.type())
print(a.size())
print(a.ndimension())
# Change dtype
a = a.type(torch.FloatTensor)
print(a.dtype)
print(a.type())

tensor(1)
torch.int64
torch.LongTensor
torch.Size([5])
1
torch.float32
torch.FloatTensor


In [2]:
b = torch.tensor([0.1, 0.2, 0.3, 0.4])
print(b.dtype)
print(b.type())

torch.float32
torch.FloatTensor


In [3]:
# Assign the data type for a tensor

c = torch.tensor([0.0, 1.0, 2.0, 3.0], dtype=torch.int32)
print(c.dtype)
print(c.type())

torch.int32
torch.IntTensor


<ipython-input-3-e9864f6cfa06>:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  c = torch.tensor([0.0, 1.0, 2.0, 3.0], dtype=torch.int32)


In [4]:
# Create a specific tensor type

d = torch.FloatTensor([0, 1, 2, 3])
print(d.dtype)
print(d.type())

torch.float32
torch.FloatTensor


In [5]:
# Change dimension

e = torch.Tensor([0,1,2,3,4,5])
e_col = e.view(6, 1) # view(# of rows, # of cols)
print(e_col.ndimension())
e_col = e.view(-1, 1) # -1 means auto
print(e_col.ndimension())
e_col = e.view(1, 6)
print(e_col.ndimension())

2
2
2


## Conversion of Tensors

### Convert between tensor and numpy array

In [6]:
import numpy as np

numpy_array = np.array([0.0, 1.0, 2.0, 3.0])
torch_tensor = torch.from_numpy(numpy_array)
print(torch_tensor)
back_to_numpy = torch_tensor.numpy()
print(back_to_numpy)

tensor([0., 1., 2., 3.], dtype=torch.float64)
[0. 1. 2. 3.]


### Convert between tensor and pandas

In [7]:
import pandas as pd

pandas_series = pd.Series([0, 1, 2, 3])
pandas_to_torch = torch.from_numpy(pandas_series.values)
print(pandas_to_torch)

tensor([0, 1, 2, 3])


### Convert between tensor and python list

In [8]:
this_tensor = torch.tensor([1, 2, 3])
torch_to_list = this_tensor.tolist()
print(torch_to_list)

[1, 2, 3]


### Element of tensor

In [9]:
new_tensor = torch.tensor([5, 4, 3, 2])
print(new_tensor[0])

# To get value of tensor

print(new_tensor[0].item())

tensor(5)
5


# Index and slicing