<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Two-Dimension-Tensors" data-toc-modified-id="Two-Dimension-Tensors-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Two Dimension Tensors</a></span><ul class="toc-item"><li><span><a href="#Create-2D-Tensors" data-toc-modified-id="Create-2D-Tensors-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Create 2D Tensors</a></span></li><li><span><a href="#Index-and-Slicing-of-2D-Tensors" data-toc-modified-id="Index-and-Slicing-of-2D-Tensors-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Index and Slicing of 2D Tensors</a></span></li><li><span><a href="#Basic-Operations-in-2D-Tensors" data-toc-modified-id="Basic-Operations-in-2D-Tensors-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Basic Operations in 2D Tensors</a></span></li><li><span><a href="#Product-of-Two-Tensors" data-toc-modified-id="Product-of-Two-Tensors-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Product of Two Tensors</a></span></li><li><span><a href="#Matrix-Multiplication" data-toc-modified-id="Matrix-Multiplication-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Matrix Multiplication</a></span></li></ul></li></ul></div>

# Two Dimension Tensors

## Create 2D Tensors

In [1]:
import torch

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

A = torch.tensor(a)
print(A)

print(A.ndimension())
print(A.shape)
print(A.size())
print(A.numel()) # number of element

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
2
torch.Size([3, 3])
torch.Size([3, 3])
9


## Index and Slicing of 2D Tensors

In [2]:
print(A)
print(A[1][2])
print(A[0][0])

print(A[0, 0:2])
print(A[1:3, 2])

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
tensor(23)
tensor(11)
tensor([11, 12])
tensor([23, 33])


## Basic Operations in 2D Tensors

In [3]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]])

Z = X + Y
print(Z)

tensor([[3, 1],
        [1, 3]])


In [4]:
Y = torch.tensor([[2, 1], [1, 2]])

Z = 2 * Y
print(Z)

tensor([[4, 2],
        [2, 4]])


## Product of Two Tensors
$u 	\circ v$

[阿達瑪乘積 (矩陣)](https://zh.wikipedia.org/wiki/%E9%98%BF%E9%81%94%E7%91%AA%E4%B9%98%E7%A9%8D_(%E7%9F%A9%E9%99%A3))

In [5]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]])

Z = X * Y
print(Z)

tensor([[2, 0],
        [0, 2]])


## Matrix Multiplication
$AB$

$A: m \times n$

$B: n \times p$

[矩陣乘法](https://zh.wikipedia.org/wiki/%E7%9F%A9%E9%99%A3%E4%B9%98%E6%B3%95)

In [6]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])

C = torch.mm(A, B)
print(C)

tensor([[0, 2],
        [0, 2]])
